---
- include_vars: vars.yml

- name: Create base directories
  file:
    path: /opt/cnf_testbed/{{ use_case }}/{{ item }}
    state: directory
  with_sequence: count="{{ cnf.cnfs }}"

- name: Get VLANs if using Mellanox
  shell: cat /etc/vpp/setup.gate | grep sub | awk '{print $4}'
  register: vlan_out
  when: not intel_nic

- name: Create VLAN array
  set_fact:
    vlans: "{{ vlan_out.stdout_lines }}"
  when: not intel_nic

- name: Update host vSwitch configuration file
  template:
    src: "{{ use_case }}/setup.gate.j2"
    dest: /etc/vpp/setup.gate

- name: Restart VPP container
  command: docker restart vppcontainer
  when: vppc

- name: Restart VPP service
  service:
    name: vpp
    state: restarted
  when: vpps

- name: Push CNF templates 1/2
  template:
    src: "{{ use_case }}/{{ item }}/setup.gate.j2"
    dest: "/opt/cnf_testbed/{{ use_case }}/{{ item }}/setup.gate"
  with_sequence: count="{{ cnf.cnfs }}"

- name: Push CNF templates 2/2
  template:
    src: "{{ use_case }}/startup.conf.j2"
    dest: "/opt/cnf_testbed/{{ use_case }}/{{ item }}/startup.conf"
  with_sequence: count="{{ cnf.cnfs }}"

- name: Start CNFs (Docker)
  docker_container:
    name: "CNF_{{ item }}_{{ use_case }}"
    image: soelvkaer/vppcontainer:latest
    privileged: true
    devices:
      - "/dev/hugepages/:/dev/hugepages/:rwm"
    volumes:
      - /etc/vpp/sockets/:/root/sockets/
      - "/opt/cnf_testbed/{{ use_case }}/{{ item }}/:/etc/vpp/"
  with_sequence: count="{{ cnf.cnfs }}"
  when: not k8s

- name: Restart VPP container (Post-deploy)
  command: docker restart vppcontainer
  when: vppc and not k8s
 
- name: Restart VPP service (Post-deploy)
  service:
    name: vpp
    state: restarted
  when: vpps and not k8s
