---
- name: find the controller host address
  set_fact:
    host_0_address: "{{hostvars[groups['all'][0]].ansible_bond0.ipv4.address}}"
    bond0_addr: "{{ansible_bond0.ipv4.address|ipmath(1)}}/{{ansible_bond0.ipv4.netmask}}"

- name: add hostname to /etc/hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '^.*{{inventory_hostname}}.*$'
    line: '{{inventory_hostname}}    {{ansible_hostname}}'

# TODO: report bug for this
- name: Add vpp log dir
  file:
    path: /var/log/vpp
    state: directory
  when: vpp_ver >= 1904

- name: update plugins config for vpp
  template:
    src: ml2_conf.j2
    dest: /etc/neutron/plugin.ini
    mode: 0644
  when: ansible_os_family == 'RedHat'

- name: update plugins config for vpp
  template:
    src: ml2_conf.j2
    dest: /etc/neutron/plugins/ml2/ml2_conf.ini
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: switch to vpp-router
  ini_file:
    dest: /etc/neutron/neutron.conf
    section: DEFAULT
    option: service_plugins
    value: vpp-router
  when: host_0_address == inventory_hostname

- name: add missing network params to nova.conf
  ini_file:
    dest: /etc/nova/nova.conf
    section: DEFAULT
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - {option: 'vif_plugging_timeout', value: '300' }
    - {option: 'vif_plugging_is_fatal', value: 'True' }
    - {option: 'use_neutron', value: 'True' }
    - {option: 'firewall_driver', value: 'nova.virt.firewall.NoopFirewallDriver' }
    
- name: add missing scheduler params to nova.conf
  ini_file:
    dest: /etc/nova/nova.conf
    section: scheduler
    option: "{{item.option}}"
    value: "{{item.value}}"
  with_items:
    - {option: 'scheduler_driver_task_period', value: '60' }
    - {option: 'scheduler_driver', value: 'nova.scheduler.filter_scheduler.FilterScheduler' }
    - {option: 'schedulr_available_filters', value: 'nova.scheduler.filters.all_filters' }
    - {option: 'scheduler_default_filters', value: 'RetryFilter, AvailabilityZoneFilter, RamFilter, DiskFilter, ComputeFilter, ComputeCapabilitiesFilter, ImagePropertiesFilter, ServerGroupAntiAffinityFilter, ServerGroupAffinityFilter, NUMATopologyFilter' }
    
- name: install bridge utilities package - RedHat
  yum:
    name: bridge-utils
  when: ansible_os_family == 'RedHat'

- name: install bridge utilities package - Debian
  apt:
    name: bridge-utils
  when: ansible_os_family == 'Debian'

- name: enable python pip - RedHat
  yum:
    name: ['python-devel','python-pip']
  when: ansible_os_family == "RedHat"

- name: enable python pip - Debian
  yum:
    name: ['python-dev','python-pip']
  when: ansible_os_family == "Debian"

- name: get vpp plugin code
  git:
    repo: https://github.com/openstack/networking-vpp
    dest: /root/networking-vpp
    version: "{{vpp_branch}}"
    update: no

- name: see if l3 unicode bug is in vpp code
  replace:
    path: /root/networking-vpp/networking_vpp/services/l3_router/l3_vpp.py
    regexp: "ip_network.*subnet.*cidr.*"
    replace: ip_network(unicode(subnet['cidr']))

- name: install new vpp python api pre-req vpp_ver 19.04+ into python 2.7
  pip:
    name: aenum
    executable: pip2
  when: vpp_ver >= 1904 and not vpp_src

- name: install openstack networking-vpp plugin
  pip:
    name: /root/networking-vpp

- name: migrate neutron vpp database
  command: neutron-db-manage --subproject networking-vpp --config-file /etc/neutron/neutron.conf --config-file /etc/neutron/plugins/ml2/ml2_conf.ini upgrade head
  when: host_0_address == inventory_hostname

#- name: bring ex-slave interface down
#  command: ip l s dev {{vlan_interface}} down
#  ignore_errors: true

- name: Install ethtool
  apt:
    name: ethtool
  when: ansible_os_family == "Debian" and vpp_ver >= 1904 and not vpp_src

# Create veth pair for uplink due to deprecated tap cli
# source: https://github.com/midonet/ansible-midonet-gateway/blob/master/tasks/static_uplink.yml
- name: Grab ip link status
  command: ip link
  register: ip_link
  changed_when: False

- name: Create veth pair
  command: ip link add vpp0 type veth peer name uplink
  when: '"vpp0" not in ip_link.stdout and vpp_ver >= 1904 and not vpp_src'

- name: Set uplink up
  command: ip link set uplink up
  when: '"vpp0" not in ip_link.stdout and vpp_ver >= 1904 and not vpp_src'

- name: Set vpp0 up
  command: ip link set vpp0 up
  when: '"vpp0" not in ip_link.stdout and vpp_ver >= 1904 and not vpp_src'

- name: Disable rx/tx checksumming on uplink
  command: ethtool -K uplink rx off tx off
  when: '"vpp0" not in ip_link.stdout and vpp_ver >= 1904 and not vpp_src'

- name: add vpp-agent script
  template:
    src: vpp-agent
    dest: /usr/local/bin/vpp-agent
    mode: 0755

- name: add vpp-agent systemd service - RedHat
  template:
    src: vpp-agent-redhat.service
    dest: /usr/lib/systemd/system/vpp-agent.service
    mode: 0644
  when: ansible_os_family == 'RedHat'

- name: add vpp-agent systemd service - Debian
  template:
    src: vpp-agent-debian.service
    dest: /lib/systemd/system/vpp-agent.service
    mode: 0644
  when: ansible_os_family == 'Debian'

- name: add vpp-agent multi-user.wants link - RedHat
  file:
    state: link
    src: /usr/lib/systemd/system/vpp-agent.service
    dest: /etc/systemd/system/multi-user.target.wants/vpp-agent.service
  when: ansible_os_family == 'RedHat' and inventory_hostname == host_0_address

- name: add vpp-agent multi-user.wants link - Debian
  file:
    state: link
    src: /lib/systemd/system/vpp-agent.service
    dest: /etc/systemd/system/multi-user.target.wants/vpp-agent.service
  when: ansible_os_family == 'Debian'

- name: ensure rootwrap.d folder exists
  file:
    path: /etc/neutron/rootwrap.d/
    state: directory

- name: ensure linuxbridge rootwrap neutron filters exist
  template:
    src: linuxbridge.filters
    dest: /etc/neutron/rootwrap.d/linuxbridge.filters
    mode: 0755

- name: add hugepage support for nova
  ini_file:
    path: /etc/nova/nova.conf
    section: DEFAULT
    option: reserved_huge_pages
    value: node:0,size:2048,count:64

- name: ensure Hugepages are properly sized (2K 2K pages)
  template:
    src: 80-vpp.conf
    dest: /etc/sysctl.d/80-vpp.conf
  register: hugepages

- name: reload vpp hugepage support
  command: sysctl --system
  when: hugepages.changed

- name: ensure Neutron plugin is defined - Debian
  lineinfile:
    path: /etc/default/neutron-server
    regexp: 'NEUTRON_PLUGIN_CONFIG=.*'
    line: 'NEUTRON_PLUGIN_CONFIG=/etc/neutron/plugins/ml2/ml2_conf.ini'
  when: ansible_os_family == 'Debian' and inventory_hostname == host_0_address

- name: verify that openstack dashboard is accessible to apache
  file:
    path: /var/lib/openstack-dashboard
    state: directory
    mode: 0777

- name: Ensure current python eventlet is installed
  pip:
    name: eventlet
    version: 0.22

# This should no longer be neccesary thanks to update to multinode.json default_attributes["openstack"]["mysql"]["max_connections"] = 1451
# - name: update mysql thread pool to 1451
#   lineinfile:
#     dest: /etc/mysql/conf.d/openstack.cnf
#     regexp: '^.*max_connections =.*$'
#     line: 'max_connections = 1451'
#   when: host_0_address == inventory_hostname

- name: stop vpp and vpp-agent
  service:
    state: stopped
    name: "{{item}}"
  with_items: ['vpp','vpp-agent'] 

- name: restart etcd
  service:
    name: etcd
    state: restarted

- name: restart services on controller
  service:
    state: restarted
    name: "{{item}}"
  with_items: "{{['mysql','rabbitmq-server','apache2','neutron-server'] if ansible_os_family == 'Debian' else ['mysql','rabbitmq-server','neutron-server']}}"
  when: host_0_address == inventory_hostname
  
- name: restart services on compute
  service:
    state: restarted
    name: nova-compute
  when: not host_0_address == inventory_hostname and ansible_os_family == 'Debian'

- name: restart services on compute
  service:
    name: openstack-nova-compute
    state: restarted
  when: not host_0_address == inventory_hostname and ansible_os_family == 'RedHat'

- name: start vpp and vpp-agent
  service:
    state: restarted
    name: "{{item}}"
  with_items: ['vpp','vpp-agent'] 
