---
- hosts: all
  vars:
    vpp_network: true
    vpp_ver: 1904 # vpp ver for binary install
    vpp_branch: '19.03' # ver for networking-vpp
    vpp_commit: stable/1807 # vpp ver for source build
    vpp_vxlan: false
    create_vlans: true
    create_masquerade: true
    vlans:
      k8sworkervlan1:
        interface: "eth1"
      k8sworkervlan2:
        interface: "eth1"


  pre_tasks:
  - setup:
  - name: Check for Mellanox ConnectX inteface
    shell: cat /proc/bus/pci/devices | cut -f1 | grep 5e00
    register: mellanox
    ignore_errors: true

  - name: Get Bond0 Slave0 interface
    set_fact:
      vlan_interface: "{{ansible_bond0.slaves[0]}}"
    when: ansible_bond0.slaves[0] is defined

  - name: set vpp interface name for Mellanox
    set_fact:
      vpp_interface: TwentyFiveGigabitEthernet5e/0/1
      vpp_src: true
    when: mellanox.rc == 0

  - name: set vpp interface name for Intel
    set_fact:
      vpp_interface: TenGigabitEthernet1a/0/1
      vpp_src: false
    when: not mellanox.rc == 0

  roles:
    - role: packet_l2
      delegate_to: localhost
      run_once: true
      connection: local
      vars:
        facility: "{{ lookup('env','PACKET_FACILITY') }}"
        deploy_env: "{{ lookup('env','DEPLOY_ENV') }}"
        server_list: "{{ lookup('env','SERVER_LIST') }}"
        project_name: "{{ lookup('env','PROJECT_NAME') }}"
      when: create_vlans

    - role: retr0h.etcd
      vars:
        etcd_interface: bond0
        etcd_checksum: dc5d82df095dae0a2970e4d870b6929590689dd707ae3d33e7b86da0f7f211b6.
        etcd_version: v3.3.12
      when: vpp_network

    - role: chef_openstack_install
    - role: openstack_ovs_provider
      when: not vpp_network
    - role: openstack_vnc_fix

    - role: vpp_src_install
      when: vpp_network and vpp_src
    - role: vpp_install
      when: vpp_network and not vpp_src
    - role: vpp_openstack
      when: vpp_network
    - role: openstack_scripts
