---
galaxy_info:
  author: John Dewey
  description: Install and manage etcd.
  company:
  license: MIT
  min_ansible_version: 2.1
  platforms:
  - name: Ubuntu
    versions:
    - all
    - quantal
    - raring
    - saucy
    - trusty
    - xenial
  - name: EL
    versions:
    - 7
  categories:
  - system
dependencies: []
